- name: Install Semaphore
  community.docker.docker_container:
    name: semaphore
    image: semaphoreui/semaphore:latest
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    volumes:
      - "semaphore_data:/var/lib/semaphore"
      - "semaphore_config:/etc/semaphore"
    env:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      ANSIBLE_HOST_KEY_CHECKING: "False"
