- name: Install Homepage in Docker
  community.docker.docker_container:
    name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    volumes:
      - /home/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /home/docker/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    networks:
      - reverse_proxy
