---
- name: Setup minecraft on docker.
  hosts: all
  become: true
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter become pass"
  roles:
    - role: docker
    - role: minecraft
