---
- name: Setup debian with standard configuration.
  hosts: localhost
  vars_prompt:
  - name: ansible_become_pass
    prompt: "Enter become pass"
  roles:
    - role: debian-template
    - role: server_setup
      when: ansible_connection == "ssh"
      become: true
